### PR TITLE
Add PHP 7.3 and remove checkver from 5.6, 7.0

### PR DESCRIPTION
**Pull request by niheaven**
I don't use PHP with scoop, so just fix `checkver`.

### CODE REVIEW

**Comment by r15ch13** [comment]
Please add the checkver back for older versions. They still can get security fixes (even if they are EOL)
Older versions are located in https://windows.php.net/downloads/releases/archives/

**Comment by niheaven** [comment]
- Change `bucketdir` to `Find-BucketDirectory`
- Add `suggest` according to filename (`VC9`: `vcredist2008`, `VC11`: `vcredist2012`, `VC14`, `VC15`: `vcredist2019`)
- Fix PHP 5.6 and PHP 7.0 url

`checkver` couldn't work in https://windows.php.net/downloads/releases/archives/, the filename there aren't sorted by datetime, but simple alphabeta order. So for security fixes, the manifests need manually update.

**Comment by r15ch13** [comment]
Ping via https://github.com/ScoopInstaller/PHP/issues/2

**Comment by niheaven** [comment]
This is ready to merge. Old versions' `checkver` are unrealizable 😭

**Pull request merged**
